[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_renet = "1.0"
bincode = "1.3"
serde = { version = "1", features = ["derive"] }
