name: Release Container

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-server-container:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: multiplayer-bevy-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -f server.Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG -t ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest
